### ISSUE TITLE
can't install macrogauracore to /usr/bin

### ISSUE THREAD

**Issue by trankimlonghai** [black-dragon74/macRogAuraCore#2]
https://imgur.com/C3zruqG

Hi, I can't install macrogauracore into /usr/bin on Catalina 10.15.7, disabled SIP and gatekeeper, but it won't help.

**Comment by black-dragon74** [comment]
In recent versions of macOS, it's supposed to be installed at `/usr/local/bin`

Please install it manually there. I'll update the script to reflect the same.

**Comment by trankimlonghai** [comment]
Cool, I've just copied/installed as you guided me at /usr/local/bin , everything seems okay, it works now, thanks, nice day! ^^

**Comment by black-dragon74** [comment]
Fixed at 116eef972a38285732a90fc77c3e61cfe18a7ef8 ✅
